apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracking-api
  template:
    metadata:
      labels:
        app: tracking-api
    spec:
      containers:
        - name: tracking-api
          image: your-dockerhub-username/tracking-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-api
spec:
  selector:
    app: tracking-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
