spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: tracking-consumer-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    host: redis
    port: 6379
